# Generated by Django 2.2.6 on 2019-11-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gluck', '0002_auto_20191104_1607'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={},
        ),
        migrations.RemoveField(
            model_name='section',
            name='image',
        ),
        migrations.RemoveField(
            model_name='section',
            name='text',
        ),
        migrations.AlterField(
            model_name='section',
            name='section_title',
            field=models.TextField(default='section title', max_length=200),
        ),
    ]
