# Generated by Django 2.2.6 on 2019-11-04 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gluck', '0003_auto_20191104_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(blank=True, max_length=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('page', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gluck.Section')),
            ],
        ),
    ]
