# Generated by Django 2.2.6 on 2019-11-04 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gluck', '0006_auto_20191104_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='page',
            new_name='section',
        ),
        migrations.RenameField(
            model_name='text',
            old_name='page',
            new_name='section',
        ),
    ]
