# Generated by Django 2.2.6 on 2019-11-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gluck', '0007_auto_20191104_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='section',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
