
# Generated by Django 2.2.6 on 2019-11-04 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gluck', '0008_auto_20191104_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='section',
            new_name='section_fk',
        ),
        migrations.RemoveField(
            model_name='text',
            name='section',
        ),
        migrations.AddField(
            model_name='text',
            name='section_fk',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gluck.Section'),
        ),
    ]
