# Generated by Django 2.2.6 on 2019-11-04 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gluck', '0010_auto_20191104_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='section_title',
        ),
    ]
