# Generated by Django 2.2.6 on 2019-11-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gluck', '0014_auto_20191106_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='size',
            field=models.CharField(choices=[('M', 'Medium'), ('L', 'Large')], default='M', max_length=1),
        ),
    ]
